### ISSUE TITLE
New scheduler structure

### ISSUE THREAD

**Issue by rpanah** [iclab/centinel#135]
The current scheduler has a couple of limitations that make it less useful for us:

* a scheduler entry is identified by only one python filename, which makes it impossible to have different schedules that use the same python experiment file with different inputs/parameters
* each file is assumed to take only one file as input with a fixed name that can not be specified in scheduler file
* `scheduler.py` (on the server) is very limited in what it can schedule and the clients it can schedule on, it needs updating

As a solution, I propose a new format for our scheduler that supports the following:

* each scheduler entry is identified by a unique identifier/name, instead of a python filename
* each scheduler entry can specify multiple python experiments
* each scheduler entry can specify multiple input files per python experiment
* each scheduler can pass an argument dictionary to experiment files that support it
* 'scheduler.py' can schedule things on clients in a certain country and/or globally, by using country-specific as well as global experiment and data folders

If we want to have a good paper, I think it is very important that we collect data now that we have test nodes as well as VPN clients out there ready to run our experiments. I'll be pushing a new package version to roll out the new baseline experiments to all clients once I'm done re-implementing the scheduler and I'd appreciate it if people gave me their thoughts and feedback on this proposal soon.

@phillipa, @feamster, and @ben-jones, can you guys please let me know what you think?

**Comment by phillipa** [comment]
I like the unique identifier idea and the configurable argument files plan. 

In terms of unique identifier it might be optimal if the identifier is a numerical value or something that will be unique. Maybe users can give the thing a name to make working with things easier or we can just not expose that. Basically you say 'i want to make a test, using this python, these input files, run it from day A to day B with F frequency' [go]. internally the system can make an id for it.

**Comment by ben-jones** [comment]
Whenever we are building a system, there is a fundamental tradeoff between utility (how much can we do) and complexity (how difficult is the system to maintain). I can see the value of a lot of this functionality, but it breaks our existing conventions for how we schedule files. I'm fine with breaking backwards compatibility, but if we do break compatibility, we need to *extensively* test the system to make sure everything works. The advantage of the current scheduler is that it never changes what the Centinel runner expects; the Centinel experiment runner only sees the same Python files with the same input files it expected before. If we break from this model, then we need to do extensive integration testing to make sure that everything works.

It seems like the added functionality may justify the complexity cost, but we need to really consider how to do this in the most simple manner possible. What is the point of having a unique identifier? Why do we need an identifier? Why can't I specify the scripts I want to run without an identifier?

I also buy the ability to run multiple measurements and multiple experiment files for each thing in the scheduler (I think we would call this abstraction an experiment).

I also agree that it would be nice to have a cleaner way to schedule by country (currently, we schedule to an entire country by copying the file to each of the experiment directories), but a) there are difficulties that we need to resolve here (e.g. how do we handle scheduling on devices that roam between countries) and b) it's unclear that pulling from multiple directories makes the problem any easier. For b), we are currently copying into each client's directory before shipping experiments. In your proposed scheme, we would create some directory for each country or each experiment (defined in terms of the abstraction above). However, this doesn't really make the problem any easier; you still have to copy all of the files into some logical abstraction of the client directory to ship experiments to the client. Is this really that different from what we have and is the extensive time needed to troubleshoot this change worth the effort? (I'm not begging the question, I'm proposing a topic for future discussion).

**Comment by phillipa** [comment]
My feeling is that the unique identifier is something that would be applied internal to the system to keep different runs of the same python test separate. 

Let's chat more in today's meeting?
