### ISSUE TITLE
Update tcpdump to split up pcap for each test

### ISSUE THREAD

**Issue by ben-jones** [iclab/centinel#141]
Currently, our script collects a single pcap for all of the tests in an experiment, creating a single enormous pcap that is difficult to analyze. We made the design decision to collect a single pcap of the entire experiment because 1) it let us drop root privileges for most of the experiment, 2) it let us cut out the time for starting and stopping tcpdump, and 3) there was no other way to capture traffic for the concurrent HTTP measurements. The concurrent HTTP sessions will generate traffic to multiple destinations and will be difficult to predict where the traffic will go for each connection (imagine following redirects to a blockpage). This means that we cannot pull traffic for each measurement after the experiment finishes, so we are stuck with a single pcap if we do concurrent HTTP measurements.

At the cost of speed, we should offer the option to get a pcap for each measurement (when doing serial, not concurrent measurements) by either a) stopping and starting tcpdump for each measurement or b) waiting a second between each measurement and segmenting the pcap based on time.

**Comment by rpanah** [comment]
@ben-jones did you read the [code](https://github.com/iclab/centinel/blob/master/centinel/experiments/baseline_linear.py)?

**Comment by ben-jones** [comment]
@rpanah, you linked me to a single experiment and tcpdump is not baked into the primitive. We should offer the option to collect a pcap with each primitive and this doesn't address my second point; segmenting the pcap by time to avoid the overhead of starting and stopping the capture.

**Comment by rpanah** [comment]
While tcpdump is not baked into the primitive itself, the experiment is a serial version of the experiment which does have tcpdump baked into it (line 178) and in each pcap, you'll get DNS, TLS, traceroute, and HTTP for a _single_ URL.
To address your second point, the serial version does have a timeout between different tcpdump sessions.

**Comment by ben-jones** [comment]
I agree that tcpdump is a part of that experiment, but I am going to start writing analysis code and it will be *much* easier if I have a separate pcap for each individual measurement like an HTTP test.

The reason I mentioned the timeout is that we can have a much shorter timeout if we do a single pcap, then segment based on time at the end.

**Comment by rpanah** [comment]
> ... it will be much easier if I have a separate pcap for each individual measurement like an HTTP test.

Wouldn't modifying the serial version of baseline (e.g. adding more tcpdump start/stop points) yield the same result?
The same could be said about timeout.

**Comment by ben-jones** [comment]
I could do the same thing by modifying that experiment, but I think I extend each primitive with the option to get a pcap and segment the entire pcap just before uploading the result.

**Comment by phillipa** [comment]
How is resolving this going? I remember when Yubo started analyzing data, splitting the pcaps was a headache, but part of the reason it all ended up grouped together in the baseline was because it was taking too long if we started/stopped the pcaps. I like the idea of being able to toggle it on a per-primitive basis.

**Comment by ben-jones** [comment]
Unfortunately, I had to preempt on these fixes for an emergency on another project. I think it will be possible to do one pcap, then use a replay filter to get the content back at the end. Unfortunately, this will prevent us from running measurements in parallel, which would already have been a problem, because we can't separate out the data for each site. For example, I was talking with @jakubd and he mentioned that one pcap had hundreds of URLs in it, so much too long to go through manually afterwards.

**Comment by phillipa** [comment]
We had discussions about all of this when we implemented the tcpdump in the platform initially. In the end I think we opted for the approach that allowed parallelism/required parsing out the relevant data. @abbas might remember more of the details of this.

**Comment by rpanah** [comment]
@phillipa it was like that initially (and I have kept the code). We used to have a single pcap for each and every URL. But @ben-jones argued that (pull request #124):

> I disagree with this. What is a clean pcap to you? By default, we collect everything, then we can strip off what we don't need. This means that any updates, command and control traffic, and anything else are going to be caught in the pcap, which won't be clean (meaning that other concurrent traffic will be captured by centinel.) We can add code to get rid of this, but it's probably not worth it.

> Also, I don't buy that this is necessary. What is the value in having a "clean" pcap? Why would that make analysis any easier? To do a robust analysis, we are going to have to apply higher level information (e.g. matching DNS queries and responses by query ID), so it shouldn't make a difference how much stuff is being requested concurrently.

**Comment by rpanah** [comment]
Also, this from @ben-jones (PR #124):

> Concurrency shouldn't be an issue for us either at the collection or the analysis stage. If we assume that we are on RPIs, which we previously have, then we can safely collect all traffic to target ports without an risk of collecting user data. For example, we could collect all the data or just collect all of the packets destined for port 53 to get all DNS traffic. Additionally, concurrency won't be an issue at the analysis stage because a) bro is awesome for analyzing pcaps will give us a log of all of the DNS requests and responses in the pcap and b) it is really easy to correlate DNS requests and responses. DNS packets contain a query ID field that must match between the query and response and the responses often contain the original question, making identification even easier.

> Basically, I don't see a strong argument for not using concurrency. If we have concurrency, then there is no reason to reduce the timeout.

**Comment by rpanah** [comment]
@phillipa, so I guess it did become "an issue".

**Comment by feamster** [comment]
I think you can just capture a single pcap and split it upon analysis.  This seems a little bit cleaner; otherwise, you'll have to take a pcap for every single experiment.  

Of course, somehow there has to be a way to know which measurements were run when a pcap was taken.  But, with the appropriate metadata, this seems solvable?

Why does one pcap with hundreds of URLs pose a problem?  Simply split the pcap post hoc and parallelize your analysis at that point. If you can't handle a pcap with hundreds of URLs, there's probably an issue with analysis.

**Comment by phillipa** [comment]
Yep. This is the solution Abbas had implemented. Many tests in one pcap. Yubo has analysis code that can handle it.

**Comment by feamster** [comment]
So, what's the problem?

**Comment by phillipa** [comment]
I think Ben is suggesting we implement the option to do a single pcap per experiment as an extra option to make analysis easier. I don’t think there is a problem.

**Comment by feamster** [comment]
Option (b): " b) waiting a second between each measurement and segmenting the pcap based on time." seems easy enough to do...

**Comment by rpanah** [comment]
@phillipa I have written code for both scenarios while at Citizen Lab. One can slightly tweak my non-concurrent version of the baseline experiment to support per-primitive tcpdump using the existing experiment standard. It's a matter of adding a few lines of code to it. Enabling/disabling tcpdump for each experiment can be implemented using experiment config flags (look at this [wiki entry](https://github.com/iclab/centinel/wiki/Scheduler-format)).

**Comment by phillipa** [comment]
@Abbas. Cool. Sounds like you have it already implemented so Ben should only have to edit a few lines of code here. I couldn’t remember where we had left it off.

**Comment by ben-jones** [comment]
The reason that I bring this up now is that there is a disconnect between users like @jakubd and the developers. Having a pcap with a few hundred URLs can be difficult to analyze and we need to make the analysis process as streamlined as possible. We need to build an automated framework for analysis, but we also need to make the platform usable by those who do analysis on top every day. Additionally, analyzing the several hundred URL pcap programmatically requires handling a number of tricky edge cases and I'm worried that we are going to miss cases. If the best solution is for someone to manually analyze the pcap, then we should try to support that.

Also, I wrote the tcpdump code with the intention of letting users start and stop as many pcaps as they want, but my suggested design is to do a single capture, then segment on time, not flow. I wrote the pcap primitive so that you can specify a post capture filter to parse down the pcap. The postcapture format would let you do things like only get the packets associated with the Centinel process (tcpdump's -Q flag lets you capture based on process name or id), but we would need to add support for [editcap](https://www.wireshark.org/docs/man-pages/editcap.html) in order to segment based on time.

**Comment by feamster** [comment]
Can you elaborate on what analysis needs to be done on the pcap?  Perhaps one approach is to provide the tools that support whatever they're trying to do with centinel, rather than changing how the measurements are collected.

**Comment by rpanah** [comment]
> Perhaps one approach is to provide the tools that support whatever they're trying to do with centinel, rather than changing how the measurements are collected.

+1
