### ISSUE TITLE
Can't consent any longer

### ISSUE THREAD

**Issue by jakubd** [iclab/centinel#152]
To replicate run:

```
./centinel-dev --sync
```

And visit the consent URL at 
https://server.iclab.org:8082/consent/ + whatever typeable handle

and get greeted with

```
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

This might be related to the move from bottle to wsgi proper.

**Comment by rpanah** [comment]
This should be on the server issue tracker. I have fixed this [here](https://github.com/iclab/centinel-server/pull/86).

**Comment by ben-jones** [comment]
closing this because it is a server issue and is now closed there
