### ISSUE TITLE
tcpdump doesn't support vpn walker

### ISSUE THREAD

**Issue by lianke123321** [iclab/centinel#153]
Centinel code for starting tcpdump doesn't specify an interface to listen to, which results in all captured packets being encrypted when running vpn walkers, because it's listening to default interface instead of the vpn tunnel.

I'm working on this and hopefully I could fix it by today.

**Comment by ben-jones** [comment]
this should be fixed by #154. You can specify a global tcpdump interface option in the config file, which will be something like "-i tun0"

**Comment by lianke123321** [comment]
Cool. @ben-jones you could close this issue then.
