### ISSUE TITLE
Some output json files don't include GET requests (but include traceroutes and DNS requests for the same URL)

### ISSUE THREAD

**Issue by jakubd** [iclab/centinel#165]
I have some output JSON files from centinel that are the result of running the baseline experiment.  What is odd about them is that we see a URL and associated traceroutes and DNS results for them but they are missing associated GET requests.  From my understanding, even if a GET fails this should be recorded but the json files I am looking at don't seem to match  that assumptions  Will share the jsons offline along with samples of the URLs out of band.

**Comment by rpanah** [comment]
Looks like the threads created for different URLs are being terminated prematurely. This also happens for some traceroutes as well (empty results).
I think since threading also causes issues with pcap post-processing, it would be better to just use the linear version of the baseline with individual pcaps instead. I'll make sure that one is up-to-date and functional before you guys use it.

**Comment by phillipa** [comment]
Does this mean the concurrent version is buggy/should be considered deprecated?

**Comment by rpanah** [comment]
@phillipa, yes. I've pointed this out before. Adrian and I are working on improving the linear version. That one should be used instead.

**Comment by phillipa** [comment]
If this solves the bug shall the issue be closed? Jakub let us know if there are more issues with the linear version?

**Comment by lianke123321** [comment]
I have some updates in leakage doc. I found bugs during experiment and I don't know if there are more.

**Comment by phillipa** [comment]
Did you fix the bugs that you found? Please update.

Phillipa Gill, Assistant Professor
Dept. of Computer Science
Stony Brook University, SUNY
http://www.cs.stonybrook.edu/~phillipa <http://www.cs.stonybrook.edu/~phillipa>
http://www.nrg.cs.stonybrook.edu <http://www.nrg.cs.stonybrook.edu/>

**Comment by lianke123321** [comment]
Yes, I created a pull request for that.

**Comment by rpanah** [comment]
This has been addressed.
