### ISSUE TITLE
Basic Web UI

### ISSUE THREAD

**Issue by rpanah** [iclab/centinel#169]
what the user sees

* look at results (or simply download them)
* display scheduler
* upload/schedule experiments

**Comment by phillipa** [comment]
Repo for this : https://github.com/iclab/Centinel-new-webinterface

investigating django then integrate with summer python code.

login done by next tuesday. @ravichandrasadineni

**Comment by phillipa** [comment]
Ravi currently still debugging log in.

Plan is to have login + view table display (Eric's stuff) for all clients that log data on the server (the VPNs for now). This will require scripting Yubos code to run over the results directories and using Eric's code to translate it into the tabular output. Abbas may be helpful at pointing Ravi at the right bits of code. Most of it exists its mainly integration here.

Next Tuesday: Demo of log in + see table.

**Comment by ravichandrasadineni** [comment]
@rpanah Can you please point me to the Eric's code and Eubo's code.

**Comment by lianke123321** [comment]
Hi Ravi,

My fork of Eric's code (I made some changes after Eric left): https://github.com/lianke123321/PiResultsWebServer

Yubo's code: https://github.com/yubshang/iclab-dmp
Please use feature/add_analysis branch

**Comment by ravichandrasadineni** [comment]
Admin account Login, Logoff  and all other scenarios are handled. I am working on displaying the table. Hopefully it will be done by tomorrow.

**Comment by phillipa** [comment]
Basic UI, shows list of clients, lets you edit client info.

TODO:
o put results data in database (see separate issue)
o display results data (e.g., color coded table as discussed)
o enumerate potential attacks and how Django addresses them. Validate that this is secure enough for our purposes.

**Comment by phillipa** [comment]
By Thursday: port it to the VPN server. Have it read the VPN clients info as sample data then move on to results.

**Comment by rpanah** [comment]
We have a separate repo for this now.
