### ISSUE TITLE
DNS primitive false positive

### ISSUE THREAD

**Issue by lianke123321** [iclab/centinel#244]
DNS primitive has a serious bug that could cause reply for another domain name being accepted by the wrong thread.

**Comment by rpanah** [comment]
We should try matching the query part of the response with the actual query domain name. To clean up the data that we already have, we can use the pcaps to match the query section.

**Comment by lianke123321** [comment]
False positive is still happening. Reopen the issue.

**Comment by lianke123321** [comment]
Confirmed fix by #246
