### ISSUE TITLE
Refactor logging

### ISSUE THREAD

**Issue by ben-jones** [iclab/centinel#26]
While testing the VPN code, I discovered that the Python logging module will keep logging to the original file if you make multiple calls to logging.BasicConfig. It would be nice to address this because currently, all of the VPN logs go into 1 file.

@gsathya, let me know what you think.

**Comment by lianke123321** [comment]
I'm closing this because all VPN logs should go into one file, and it does so now. Adding additional file handler pointing to each separate VPN client log would be nice, and should be easy. I'm going to open a new issue for this.
