### ISSUE TITLE
Expanded HTTP GET Test

### ISSUE THREAD

**Issue by gsathya** [iclab/centinel#3]
One way we can go further is that a lot of implementations we see an HTTP get as done through a Python http library not a browser.  Writing the same GET request through a headless webkit browser would be more realistic representation of a users browser.  Ie - instead of just getting an HTML source of the front page it would do all the GETs of content of the page - js,images, etc.

Getting PCAPs of this kind of process would give you much richer data that is more in line with the user experience.

**Comment by feamster** [comment]
As this been done?  We could start by trying scrapy, as @gsathya suggested.

**Comment by Ashish1805** [comment]
I tried headless browser using ghost client webkit but it is giving "Segmentation Fault" for some of the websites. Issue has been opened for this on Ghost git hub <https://github.com/jeanphix/Ghost.py/issues/267>. So, I guess we cannot use ghost webkit for our experiment unless a fix for this comes. 

As per the discussion, I will try Selenium + Firefox for this experiment.

**Comment by phillipa** [comment]
Goal: Demo + unit test of this for next tuesday using selenium + FF.

**Comment by Ashish1805** [comment]
Selenium + FF script is working on Mac but when I tried Selenium + iceweasel(firefox), I am getting profile load error:

  driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 77, in __init__
    self.binary, timeout),
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 49, in __init__
    self.binary.launch_browser(self.profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 103, in _wait_until_connectable
    raise WebDriverException("Can't load the profile. Profile "
selenium.common.exceptions.WebDriverException: Message: Can't load the profile. 

I am debugging this issue but so far I dont have any luck. Any suggestions?

**Comment by rnithyanand** [comment]
I suspect that this is because of some incompatibility between the version of Iceweasel and Selenium. I suggest making sure you have the latest release of selenium on the Pi. If that doesn't work, then maybe try downgrading the version of Iceweasel you have. If none of these are working, then we can sit down and figure this out tomorrow sometime.

There are quite a few incompatible combinations of Selenium and FF. Which is why I'm still using FF 34 (Dec 2014 release) and Selenium in all my other experiments.
