### ISSUE TITLE
Create a page to show centinel's deployed client base

### ISSUE THREAD

**Issue by ben-jones** [iclab/centinel#36]
Create a page that shows centinel's deployed client base. This will be similar to networkdashboard.org.

Questions: @rpanah, @gsathya 
 * Is this visible to contributors or everyone?
 * How good is good enough for geographic aggregation?
 * Are we giving out too much info if we say whether the node is a VPN or not? This is important from a network measurement perspective, but it may identify users of the tool.

This dashboard functionality should
 * aggregate location info to the country level to prevent PII leakage

**Comment by rpanah** [comment]
This has been done.
