### ISSUE TITLE
Create a VM image with centinel preinstalled

### ISSUE THREAD

**Issue by ben-jones** [iclab/centinel#48]

**Comment by rpanah** [comment]
I have a QEMU/VirtualBox-compatilbe VM image that has centinel installed.

**Comment by ben-jones** [comment]
Where can someone access this image? Please add a link to the FAQ either under the point about installing Centinel or create a separate point about using a VM. You could host the VM somewhere like Dropbox, or we could start using the GitHub releases features. Whenever we get to a new version of Centinel, we can do a release with a pip/easy_install package, a zip of source, and a VM with the latest version of Centinel installed.

**Comment by feamster** [comment]
Maybe a docker instance, published on docker hub, might be easier, more lightweight, etc.?  As I started to dig in here again, I was thinking of publishing one image with centinel and another with centinel-dev... thoughts?

This would solve the "where can someone access this" question, as well.  Anyone searching for centinel in docker hub should be able to get up and running.

**Comment by ggmartins** [comment]
I've created a docker image for centinel at https://registry.hub.docker.com/u/ggmartins/centinel_armhf/
this is for running on raspberry pis using this image:
http://appnode.space/downloads/hypriot-rpi-20150329-140334.img.zip
you can either user appnode to run or manually pull the image using something like:
$docker pull ggmartins/centinel_armhf
$docker run -d  ggmartins/centinel_armhf "/opt/run.sh"
$docker exec -it <container> /bin/bash
let me know about your comments/suggestions..

**Comment by ben-jones** [comment]
@ggmartins, thanks so much for doing this! I still need to get caught up on docker, but this is extremely helpful!

**Comment by feamster** [comment]
@ben-jones after installing Docker, try this primer, which I put together for my SDN course:
https://www.evernote.com/l/AARM4zMeYShJZJE4WuQvZPVSv5Fp8oqa3Ug

You'll be up and running with Docker in < 1 hour.  It's fun and easy!

**Comment by lianke123321** [comment]
Done. Ask me for the image for now. It will be on the website.
