### ISSUE TITLE
update centinel package to push minimal experiment with package install

### ISSUE THREAD

**Issue by ben-jones** [iclab/centinel#79]
On package installation, we are currently installing all available experiments. This is a problem because the experiments we push with the package will be run every time that Centinel is run.

To fix this problem, we need to consider either refactoring centinel.py to not sync with the buitin experiments directory, or modify the package not to include the experiments directory. Perhaps we could add a command line parameter for whether we should check that directory? (this may be useful for testing)

Is there value in shipping a reachability test that runs every time centinel runs (it will not be possible to run centinel without the test if we choose to ship that way)

**Comment by rpanah** [comment]
Do we still want to do this? Note that we currently don't have a non-finger-printable connectivity test inside Centinel and no experiment is shipped with Centinel when installing pip package.

**Comment by ben-jones** [comment]
I don't think ping would be that big a deal, especially if we send traffic to a common target like 8.8.8.8. This type of traffic should be fairly common, so I wouldn't think it would be too fingerprintable.

**Comment by rpanah** [comment]
I agree with you in the target. But what about frequency? It might end up having a pattern that it's detectable.

**Comment by ben-jones** [comment]
I suppose that's true, though there are innumerable attacks that the censor could hit us with (e.g. see how many people request the same sites as us or see if anyone else connects to the same Tor bridge. Regardless, we should consider this in terms of a larger framework; every measurement gives us some information but costs us stealthiness. We could be perfectly stealthy and never measure, but then we wouldn't have useful data. For every primitive and measurement target (e.g. 8.8.8.8) we send traffic to, we are going to need to consider this tradeoff.

Informally, there may be a better way to do this, but I think that pings to 8.8.8.8 would be pretty stealthy. We could make the measurement more covert by randomly selecting a target from a list or choosing not to measure with some probability. We lose some information with each approach because we don't get consistent reachability measurements to the same place, but either would be more stealthy than constantly pinging 8.8.8.8.
