### ISSUE TITLE
add metadata (country, aggregated IP address, etc.) to the result file

### ISSUE THREAD

**Issue by rpanah** [iclab/centinel#92]
Call https://server.iclab.org:8082/geolocation and store the info in the result file. IMHO, this should be enabled by default.

**Comment by rpanah** [comment]
This is important since we are starting to get results back and it would be nice to have this information embedded in the results for every experiment.
I propose these fields (in order of priority):

** scheduler ID (unique scheduler identifier)
** fuzzied external IP address (using ICLab server)
** AS number and info (using ICLab server)
** country (using ICLab server)
** total running time for each experiment

@phillipa, thoughts?

**Comment by phillipa** [comment]
that seems fine to me. maybe add start and end time of the experiment?

i'm assuming we can link the scheduler id to get the rest of the data for the test.
